Add CartCommand and Handler for it
SigmaTeamProject/TeamProject pull request #16
Opened 2022-12-25 17:43 UTC by Pivanka

Добавила логіку для додавання в корзину продуктів

2022-12-25 18:16 UTC, olexiypr requested changes

2022-12-25 18:16 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        [HttpDelete("delete/{id:int}")]
для видалення ми не робимо нового маршруту

2022-12-25 18:16 UTC, olexiypr commented on Application/Commands/CartCommands/AddProduct/AddProductCommandHandler.cs
> +            cart.Items.Add(await _storageItemRepository.GetById(request.ProductId));
після додавання ми зберігаємо зміни через SaveChangesAsync()

2022-12-25 18:16 UTC, olexiypr commented on Application/Commands/CartCommands/AddProduct/AddProductCommandHandler.cs
> +            if (cart == null) throw new ArgumentException();
перевірка на нал не потрібна, ми це робимо ще в репозиторії

2022-12-25 18:16 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateCount([FromBody] UpdateProductCountDto productToUpdate) // TO ADD realization
потрібен метод який не тальки змінює кількість продуктів, а й видаляє його (загальний метод для апдейту)

2022-12-25 18:32 UTC, Pivanka commented on Application/Commands/CartCommands/AddProduct/AddProductCommandHandler.cs
> +            cart.Items.Add(await _storageItemRepository.GetById(request.ProductId));
Просто тяжко зрозуміти коли цього ще нема.

2022-12-25 18:33 UTC, Pivanka commented on WebApi/Controllers/CartController.cs
> +        [HttpDelete("delete/{id:int}")]
Але видаляємо за ідшніком?

2022-12-26 17:10 UTC, olexiypr requested changes

2022-12-26 17:10 UTC, olexiypr commented on Application/Commands/CartCommands/UpdateProduct/UpdateProductCommandHandler.cs
> +            var product = cart.Items.FirstOrDefault(await _storageItemRepository.GetById(request.ProductId));
FirstOrDefault(item => item.Product.Id == request.ProductId)

2022-12-26 17:10 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductInCartDto productToUpdate)
UpdateProductInCartDto це що?

2022-12-26 17:10 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +            var command = _mapper.Map<AddProductCommand>(productToUpdate);
мапиш в однакові команди. як я зрозумів, команда на апдейт не використовується

2022-12-26 17:10 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductInCartDto productToUpdate)
перейменувати метод на UpdateCart (ти ж апдейтиш корзину, а не продукт)

2022-12-26 17:12 UTC, Pivanka commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductInCartDto productToUpdate)
Dto яка зовні приходить, чи замінити її на шось інше?

2022-12-26 17:13 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductInCartDto productToUpdate)
я не побачив її в твоєму прі, потрібно її додати в папку Dtos

2022-12-26 17:13 UTC, Pivanka commented on WebApi/Controllers/CartController.cs
> +            var command = _mapper.Map<AddProductCommand>(productToUpdate);
це пропустила випадково, зараз зміню

2022-12-26 17:14 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductInCartDto productToUpdate)
замінювати не потрібно, потрібно просто реалізувати

2022-12-26 17:18 UTC, olexiypr requested changes

2022-12-26 17:18 UTC, olexiypr commented on WebApi/Controllers/CartController.cs
> +        public async Task<ActionResult> UpdateCart([FromBody] UpdateProductInCartDto productToUpdate)
знову ж, UpdateProductInCartDto немає в папці дто твого ПРу, його потрібно додати

2022-12-26 17:20 UTC, olexiypr requested changes

2022-12-26 17:20 UTC, olexiypr commented on Application/Commands/CartCommands/UpdateProduct/UpdateProductCommand.cs
> +    public class UpdateProductCommand : IRequest<CartModel>
також апдейт карт команд

2022-12-26 17:20 UTC, olexiypr commented on Application/Commands/CartCommands/AddProduct/AddProductCommand.cs
> +    {
AddProductCommand це команда скоріше для додавання товару, а для додавання в корзину потрібно щось типу AddProductInCartCommand

2022-12-26 18:24 UTC, olexiypr approved these changes

2022-12-26 18:24 UTC, merged