Added basic middlewares
SigmaTeamProject/TeamProject pull request #19
Opened 2022-12-26 18:04 UTC by Carineitor77

Тут ще не має con string в UseSqlServer().
Та не має залежностей (типу репозиторії)

2022-12-26 18:04 UTC, Carineitor77 commented
прикол, воно в мене ще за ті старі конфлікти ругається

2022-12-26 18:18 UTC, olexiypr requested changes

2022-12-26 18:18 UTC, olexiypr commented on WebApi/Program.cs
> +builder.Services.AddSwaggerGen(options =>
винести в окремий екстенш метод

2022-12-26 18:18 UTC, olexiypr commented on WebApi/Program.cs
> +builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
винести в окремий екстенш метод

2022-12-26 18:18 UTC, olexiypr commented on WebApi/Program.cs
> +builder.Services.AddDbContext<ApplicationDbContext>(options =>
видалити

2022-12-26 19:27 UTC, olexiypr approved these changes

2022-12-26 19:28 UTC, olexiypr requested changes

2022-12-26 19:28 UTC, olexiypr commented on Application/Commands/Auth/Login/IdentityCommandHandler.cs
> +                customer.Login == request.Login &&
пофіксити конфлікти

2022-12-26 19:56 UTC, Carineitor77 commented
Ну тут вже те, що мені треба було добавити

2022-12-27 08:40 UTC, olexiypr approved these changes

2022-12-27 08:40 UTC, merged