Feature/storege controller
SigmaTeamProject/TeamProject pull request #28
Opened 2022-12-28 00:16 UTC by Andiry-sys

Some fixes for your taskes

2022-12-28 12:39 UTC, olexiypr requested changes
я ж в попередньому рев'ю написав що потрібно виправити

2022-12-28 12:39 UTC, olexiypr commented on Application/Commands/StoregeCommands/AddProduct/AddProductInStoregeCommand.cs
> +        public string? Name { get; set; }
обов'язковий параметр

2022-12-28 12:39 UTC, olexiypr commented on Application/Commands/StoregeCommands/UpdateProduct/UpdateProdcuctInStoregeCommandHandler.cs
> +            await _productRepository.UpdateAsync(product);
воно само апдейтиться

2022-12-28 12:39 UTC, olexiypr commented on Application/Commands/StoregeCommands/UpdateProduct/UpdateProdcuctInStoregeCommandHandler.cs
> +            product.Name = request.Name;
перевірка імені на нал product.Name = request.Name ?? product.Name

2022-12-28 12:39 UTC, olexiypr commented on WebApi/Controllers/StoregeController.cs
> +            _context = context;
тут він не потрібен

2022-12-28 12:40 UTC, olexiypr commented
пофіксити всі конфлікти

2022-12-28 13:44 UTC, Andiry-sys commented
Можеш уточнити які конфлікти виникають

2022-12-28 19:31 UTC, olexiypr commented
<img width="414" alt="Featurestorege controller by Andiry-sys · Pull Request #28 · SigmaTeamProjectTeamProject" src="https://user-images.githubusercontent.com/89968042/209863124-5d484905-139c-44b3-99f1-10f07afefd3c.png">


> Можеш уточнити які конфлікти виникають, я принципі поправив шо там не добре було

2022-12-29 21:31 UTC, olexiypr commented
твій код не білдиться навіть

2023-01-01 13:11 UTC, olexiypr commented
![image](https://user-images.githubusercontent.com/89968042/210171669-fbc0757b-46fa-4e8f-a51c-1bd4e7cdbef3.png)

2023-01-01 16:52 UTC, olexiypr requested changes
все одно конфлікт є, і я, на жаль, пофіксити його не можу

2023-01-01 17:30 UTC, olexiypr approved these changes

2023-01-01 17:30 UTC, merged