Feature/testing cart controller
SigmaTeamProject/TeamProject pull request #37
Opened 2022-12-30 23:23 UTC by Pivanka

Поки додала логіку для додавання продуктів в корзину(окрім mapping, я ще над цим працюватиму). Просто глянь чи підходить такий підхід для додавання, по іншому ніяк(або запропонуй інший варіант)

2022-12-31 00:27 UTC, Pivanka commented
Тут ще досі не зроблена логіка mapping (бо там три вкладених моделі)

2022-12-31 10:11 UTC, olexiypr requested changes

2022-12-31 10:11 UTC, olexiypr commented on Application/Commands/CartCommands/ClearCart/ClearCartCommandHandler.cs
> +                .Include(cart => cart.Customer)
Кастомер не потрібен

2022-12-31 10:11 UTC, olexiypr commented on Application/Commands/CartCommands/ClearCart/ClearCartCommandHandler.cs
> +            await _cartRepository.UpdateAsync(cart);
Апдейтиться само

2022-12-31 10:11 UTC, olexiypr commented on Application/Commands/CartCommands/UpdateProduct/UpdateProductInCartCommandHandler.cs
> +            if (storageItem.Amount - request.Count < 0) throw new ArgumentException();
Якщо в реквесті буде від’ємне число, то буде помилка)

2022-12-31 10:11 UTC, olexiypr commented on Data/CartItem.cs
> +    public int ProductId { get; set; }
Якщо воно працює, то добре

2022-12-31 10:14 UTC, olexiypr commented
> Тут ще досі не зроблена логіка mapping (бо там три вкладених моделі)

Три вкладені моделі не повинно бути (це якщо вони як матрьошка вкладені), але якщо вони не як матрьошка, то їх теж не повинно бути, ми за один реквест не відправляємо скіки інфи користувачу

2022-12-31 12:06 UTC, Pivanka commented on Application/Commands/CartCommands/UpdateProduct/UpdateProductInCartCommandHandler.cs
> +            if (storageItem.Amount - request.Count < 0) throw new ArgumentException();
не буде, тому що мінус на мінус плюс)

2022-12-31 12:19 UTC, olexiypr commented on Application/Commands/CartCommands/UpdateProduct/UpdateProductInCartCommandHandler.cs
> +            if (storageItem.Amount - request.Count < 0) throw new ArgumentException();
але нормально програма не відпрацює, і в майбутньому точно буде помилка

2023-01-01 13:14 UTC, olexiypr commented on Application/Commands/CartCommands/ClearCart/ClearCartCommandHandler.cs
> +            await _cartRepository.UpdateAsync(cart);
🗿

2023-01-01 13:28 UTC, olexiypr commented
а де гет запити?) як користувачу подивиться що в нього в корзині?

2023-01-01 13:51 UTC, olexiypr commented
> а де гет запити?) як користувачу подивиться що в нього в корзині?

вже додав

2023-01-01 14:02 UTC, olexiypr approved these changes

2023-01-01 14:02 UTC, merged