Added the AuthController
SigmaTeamProject/TeamProject pull request #8
Opened 2022-12-24 16:45 UTC by Carineitor77

2022-12-24 17:07 UTC, olexiypr requested changes

2022-12-24 17:07 UTC, olexiypr commented on Business/Auth/RegisterUserCommand.cs
> +        public string Role { get; set; }
повинно бути ще одне поле підтвердження паролю, поле роль не потрібне

2022-12-24 17:07 UTC, olexiypr commented on Business/Business.csproj
> +    <TargetFramework>net7.0</TargetFramework>
ми використовуємо дотнет 6

2022-12-24 17:07 UTC, olexiypr commented on Business/Auth/IdentityCommand.cs
> +    public class IdentityCommand : IRequest<string>
перейменувати на LoginCommand

2022-12-24 17:07 UTC, olexiypr commented on WebApi/Controllers/AuthController.cs
> +            return Json(response);
в респонс додати кастомера (див. IdentityCommand), повертати Ok(response)

2022-12-24 17:07 UTC, olexiypr commented on WebApi/Controllers/AuthController.cs
> +        public async Task<IActionResult> Token([FromBody] UserModel user)
параметрами в метод передається дто, а модель повертається

2022-12-24 17:07 UTC, olexiypr commented on WebApi/Models/RegisterUserModel.cs
> +        public string? Role { get; set; }
все що й з логін моделлю

2022-12-24 17:07 UTC, olexiypr commented on Business/Auth/IdentityCommand.cs
> +    public class IdentityCommand : IRequest<string>
IRequest<(CustomerModel, string)>

2022-12-24 17:07 UTC, olexiypr commented on Business/Auth/IdentityCommand.cs
> +﻿using MediatR;
Як параметри контроллера приймаємо Дто, мапимо це в команду, з якої повертається модель

2022-12-24 17:07 UTC, olexiypr commented on Business/Auth/IdentityCommand.cs
> +
Не бачу обробника команди (public class RegisterCommandHandler : IRequestHandler<RegisterCommand, (CustomerModel, string)>)

2022-12-24 17:07 UTC, olexiypr commented on WebApi/Models/UserModel.cs
> +    public class UserModel
перейменувати на LoginDto

2022-12-24 17:32 UTC, Carineitor77 commented on WebApi/Controllers/AuthController.cs
> +            return Json(response);
Це ж медіатор має вертати токен та кастомера?
Типу кортеж, чи як?

2022-12-24 17:34 UTC, olexiypr commented on WebApi/Controllers/AuthController.cs
> +            return Json(response);
IRequest<(CustomerModel, string)>

2022-12-24 20:24 UTC, olexiypr commented on WebApi/Controllers/AuthController.cs
> +            return Json(response);
ретурн ок()

2022-12-24 20:24 UTC, olexiypr commented on Application/ViewModels/ProductVm.cs
> +﻿using Application.Mapping;
нам не потрібно вью моделс, бо у нас є моделс (вони виконують однакову роль)

2022-12-24 20:24 UTC, olexiypr commented on Application/Mapping/IMapWith.cs
> +﻿using AutoMapper;
в моєму попередньому прі є приклад як ми будемо організовувати мапінг (це видалити)

2022-12-24 20:24 UTC, olexiypr commented on Application/Dtos/RegisterUserDto.cs
> +        public string? Role { get; set; }
роль видалити

2022-12-24 20:24 UTC, olexiypr commented on Application/Commands/AddProductCommand.cs
> +﻿using Application.ViewModels;
це взагалі інша таска

2022-12-24 20:24 UTC, olexiypr commented on Application/Commands/Auth/LoginCommand.cs
> +﻿using Application.Models;
розбити функціонал логіну та реєстрації на дві папки

2022-12-24 20:24 UTC, olexiypr commented on Application/Commands/Auth/RegisterUserCommand.cs
> +    public class RegisterUserCommand : IRequest<string>
повертати токен і кастомера

2022-12-24 20:24 UTC, olexiypr commented on WebApi/Models/RegisterUserModel.cs
> +        public string? Role { get; set; }
уже є герістер юзер дто, це видалити

2022-12-25 10:35 UTC, olexiypr requested changes

2022-12-25 10:35 UTC, olexiypr commented on Application/Models/ProductModel.cs
> +    public void Mapping(Profile profile)
мапінг в окремому класі (тобі його взагалі не потрібно додавати)

2022-12-25 10:35 UTC, olexiypr commented on Application/Commands/AddProductCommand.cs
> +﻿using Application.Models;
це інший таск. через те що ти добавив цей клас, у людини яка робить цей таск будуть конфлікти в прі

2022-12-25 10:35 UTC, olexiypr commented on Application/Commands/AddProductCommand.cs
> +﻿using Application.Models;
також, щодо конфліктів, пр не повинен їх містиити

2022-12-25 10:35 UTC, olexiypr commented on Application/Commands/Auth/Registration/RegisterUserCommand.cs
> +    {
не бачу хендлера для цієї команди

2022-12-25 12:17 UTC, olexiypr requested changes

2022-12-25 12:17 UTC, olexiypr commented on Application/Commands/Auth/Login/IdentityCommandHandler.cs
> +﻿using Application.Models;
все супер, але конфліктів не повинно бути 
![image](https://user-images.githubusercontent.com/89968042/209467583-635612b1-eaa1-4fce-9f8d-319a37de179a.png)

2022-12-25 12:36 UTC, Carineitor77 commented
прикол якись

2022-12-25 12:39 UTC, Carineitor77 commented
нуу, вже меньше

2022-12-25 12:49 UTC, Carineitor77 commented
Ну там так то однакове все. Ти їх з цими конфліктами злити можеш?

2022-12-25 12:53 UTC, olexiypr commented
> Ну там так то однакове все. Ти їх з цими конфліктами злити можеш?

не можу

2022-12-25 12:55 UTC, olexiypr commented
> > Ну там так то однакове все. Ти їх з цими конфліктами злити можеш?
> 
> не можу

уже можу

2022-12-25 12:56 UTC, olexiypr approved these changes

2022-12-25 12:56 UTC, merged